all:
	mkdir bin/
	cp src/CodeGen.py bin/codegen
	cp src/GlobalVariables.py bin/GlobalVariables.py
	cp src/RegAllocatFunc.py bin/RegAllocatFunc.py
	cp src/TransInstr.py bin/TransInstr.py
	chmod +x bin/codegen
clean:
	rm -rf bin/
